// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxU7E9RNGXPt3NBfjWLqSrsmmHsswpLYg',
    appId: '1:886808501761:web:95e58e18dda43e67c66a00',
    messagingSenderId: '886808501761',
    projectId: 'solana-9663f',
    authDomain: 'solana-9663f.firebaseapp.com',
    storageBucket: 'solana-9663f.firebasestorage.app',
    measurementId: 'G-D8YGMSR9BF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh-n2X71tsFhezGiIaz9b15gUgmx0Ritc',
    appId: '1:886808501761:android:94b3e03a9f3eb268c66a00',
    messagingSenderId: '886808501761',
    projectId: 'solana-9663f',
    storageBucket: 'solana-9663f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYqMspuNORfjoqih_V-siazK3622dBhwo',
    appId: '1:886808501761:ios:5d49c0dece6a8341c66a00',
    messagingSenderId: '886808501761',
    projectId: 'solana-9663f',
    storageBucket: 'solana-9663f.firebasestorage.app',
    iosBundleId: 'com.example.flutterSolana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYqMspuNORfjoqih_V-siazK3622dBhwo',
    appId: '1:886808501761:ios:5d49c0dece6a8341c66a00',
    messagingSenderId: '886808501761',
    projectId: 'solana-9663f',
    storageBucket: 'solana-9663f.firebasestorage.app',
    iosBundleId: 'com.example.flutterSolana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxU7E9RNGXPt3NBfjWLqSrsmmHsswpLYg',
    appId: '1:886808501761:web:682099a221d432e7c66a00',
    messagingSenderId: '886808501761',
    projectId: 'solana-9663f',
    authDomain: 'solana-9663f.firebaseapp.com',
    storageBucket: 'solana-9663f.firebasestorage.app',
    measurementId: 'G-6W2J2LCESP',
  );
}
